# Generated by Django 3.2.13 on 2022-07-27 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epp', '0001_initial'),
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField(verbose_name='fecha de venta')),
                ('ConstoTotal', models.PositiveIntegerField(verbose_name='contoTotal')),
            ],
        ),
        migrations.CreateModel(
            name='VentaUnidadP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantida', models.PositiveIntegerField(verbose_name='cantidadVuP')),
                ('costo', models.PositiveIntegerField(verbose_name='contoVuP')),
                ('idPrenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenda.prendas')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
        migrations.CreateModel(
            name='VentaUnidadE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantida', models.PositiveIntegerField(verbose_name='cantidadVuE')),
                ('costo', models.PositiveIntegerField(verbose_name='contoVuE')),
                ('idEpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.epp')),
                ('idVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
