# Generated by Django 3.2.13 on 2022-09-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEpp', models.CharField(max_length=250, verbose_name='modebre epp')),
                ('tipoEpp', models.CharField(max_length=250, verbose_name='tipo epp')),
                ('tallaEpp', models.CharField(max_length=50, verbose_name='talla de epp')),
                ('precioEpp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio del epp')),
                ('fotoEpp', models.ImageField(upload_to='fotosEpp/', verbose_name='imagen de epp')),
                ('fechaEpp', models.DateTimeField(verbose_name='fecha de creacion Epp')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
