# Generated by Django 3.2.13 on 2022-09-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0003_prendas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendas',
            name='fecha',
            field=models.DateTimeField(default=None, null=True, verbose_name='fecha de creacion'),
        ),
    ]
