# Generated by Django 3.2.13 on 2022-09-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreosHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchi', models.CharField(max_length=250, verbose_name='nombre archivo')),
                ('fechaArach', models.DateField(verbose_name='fecha de envio')),
                ('id_registrousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminn.registrarusuario')),
            ],
        ),
    ]
